version: '2'
services:
  mongodb:
    image: mongo
    container_name: citas-bd
    ports:
      - "27017:27017"
    volumes:
      - "mongodata:/data/2g_citas_bd"
    networks:
      - citas-bd

volumes:
   mongodata:

networks:
  citas-bd:
